/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edangulo
 */
public class BankFrame extends javax.swing.JFrame {
    
    private ArrayList<Account> accounts;
    private ArrayList<Transaction> transactions;
    private ArrayList<User> users;
    
    /**
     * Creates new form BankFrame
     */
    public BankFrame() {
        initComponents();
        this.accounts = new ArrayList<>();
        this.transactions = new ArrayList<>();
        this.users = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelOpciones = new javax.swing.JTabbedPane();
        RegistroUsuario = new javax.swing.JPanel();
        RegistroUsuarioTituloLabel = new javax.swing.JLabel();
        RegistroUsuarioIdLabel = new javax.swing.JLabel();
        RegistroUsuarioFirstnameLabel = new javax.swing.JLabel();
        RegistroUsuarioLastnameLabel = new javax.swing.JLabel();
        RegistroUsuarioAgeLabel = new javax.swing.JLabel();
        RegistroUsuarioIdInput = new javax.swing.JTextField();
        RegistroUsuarioFirstnameInput = new javax.swing.JTextField();
        RegistroUsuarioLastnameInput = new javax.swing.JTextField();
        RegistroUsuarioAgeInput = new javax.swing.JTextField();
        RegistroUsuarioBoton = new javax.swing.JButton();
        CrearCuenta = new javax.swing.JPanel();
        CrearCuentaTituloLabel = new javax.swing.JLabel();
        CrearCuentaIdUsuarioLabel = new javax.swing.JLabel();
        CrearCuentaBalanceInicialLabel = new javax.swing.JLabel();
        CrearCuentaIdUsuarioInput = new javax.swing.JTextField();
        CrearCuentaBalanceInicialInput = new javax.swing.JTextField();
        CrearCuentaBoton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        HacerTransaccionTitulo = new javax.swing.JLabel();
        HacerTransaccionTypeLabel = new javax.swing.JLabel();
        HacerTransaccionCuentaOrigenLabel = new javax.swing.JLabel();
        HacerTransaccionCuentaDestinoLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        HacerTransaccionCuentaOrigenInput = new javax.swing.JTextField();
        HacerTransaccionCuentaDestinoInput = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        HacerTransaccionTypeInput = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RegistroUsuarioTituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegistroUsuarioTituloLabel.setText("Register User");

        RegistroUsuarioIdLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistroUsuarioIdLabel.setText("ID");

        RegistroUsuarioFirstnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistroUsuarioFirstnameLabel.setText("Firstname");

        RegistroUsuarioLastnameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistroUsuarioLastnameLabel.setText("Lastname");

        RegistroUsuarioAgeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegistroUsuarioAgeLabel.setText("Age");

        RegistroUsuarioBoton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        RegistroUsuarioBoton.setText("Register");
        RegistroUsuarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroUsuarioBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroUsuarioLayout = new javax.swing.GroupLayout(RegistroUsuario);
        RegistroUsuario.setLayout(RegistroUsuarioLayout);
        RegistroUsuarioLayout.setHorizontalGroup(
            RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroUsuarioLayout.createSequentialGroup()
                .addGroup(RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroUsuarioLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(RegistroUsuarioTituloLabel)
                        .addGap(0, 270, Short.MAX_VALUE))
                    .addGroup(RegistroUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistroUsuarioFirstnameLabel)
                            .addComponent(RegistroUsuarioLastnameLabel)
                            .addComponent(RegistroUsuarioAgeLabel)
                            .addComponent(RegistroUsuarioIdLabel))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegistroUsuarioIdInput, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegistroUsuarioLastnameInput, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegistroUsuarioAgeInput, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RegistroUsuarioFirstnameInput, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
            .addGroup(RegistroUsuarioLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(RegistroUsuarioBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistroUsuarioLayout.setVerticalGroup(
            RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroUsuarioLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(RegistroUsuarioTituloLabel)
                .addGap(18, 18, 18)
                .addGroup(RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroUsuarioIdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistroUsuarioIdLabel))
                .addGap(18, 18, 18)
                .addGroup(RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroUsuarioFirstnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistroUsuarioFirstnameLabel))
                .addGap(18, 18, 18)
                .addGroup(RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroUsuarioLastnameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistroUsuarioLastnameLabel))
                .addGap(18, 18, 18)
                .addGroup(RegistroUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistroUsuarioAgeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegistroUsuarioAgeLabel))
                .addGap(18, 18, 18)
                .addComponent(RegistroUsuarioBoton)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        PanelOpciones.addTab("Register User", RegistroUsuario);

        CrearCuentaTituloLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearCuentaTituloLabel.setText("Create Account");

        CrearCuentaIdUsuarioLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearCuentaIdUsuarioLabel.setText("User ID");

        CrearCuentaBalanceInicialLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CrearCuentaBalanceInicialLabel.setText("Initial Balance");

        CrearCuentaBoton.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        CrearCuentaBoton.setText("Create");
        CrearCuentaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCuentaBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearCuentaLayout = new javax.swing.GroupLayout(CrearCuenta);
        CrearCuenta.setLayout(CrearCuentaLayout);
        CrearCuentaLayout.setHorizontalGroup(
            CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCuentaLayout.createSequentialGroup()
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearCuentaLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(CrearCuentaTituloLabel))
                    .addGroup(CrearCuentaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearCuentaIdUsuarioLabel)
                            .addComponent(CrearCuentaBalanceInicialLabel))
                        .addGap(18, 18, 18)
                        .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CrearCuentaBalanceInicialInput)
                            .addComponent(CrearCuentaIdUsuarioInput, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(CrearCuentaLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(CrearCuentaBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CrearCuentaLayout.setVerticalGroup(
            CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearCuentaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(CrearCuentaTituloLabel)
                .addGap(18, 18, 18)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearCuentaIdUsuarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearCuentaIdUsuarioLabel))
                .addGap(18, 18, 18)
                .addGroup(CrearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearCuentaBalanceInicialInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CrearCuentaBalanceInicialLabel))
                .addGap(18, 18, 18)
                .addComponent(CrearCuentaBoton)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        PanelOpciones.addTab("Create Account", CrearCuenta);

        HacerTransaccionTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HacerTransaccionTitulo.setText("Make Transaction");

        HacerTransaccionTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HacerTransaccionTypeLabel.setText("Type");

        HacerTransaccionCuentaOrigenLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HacerTransaccionCuentaOrigenLabel.setText("Source Account");

        HacerTransaccionCuentaDestinoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HacerTransaccionCuentaDestinoLabel.setText("Destination Account");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Amount");

        HacerTransaccionCuentaDestinoInput.setToolTipText("");

        HacerTransaccionTypeInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deposit", "Withdraw", "Transfer" }));

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton3.setText("Execute");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HacerTransaccionTypeLabel)
                            .addComponent(jLabel13)
                            .addComponent(HacerTransaccionCuentaDestinoLabel)
                            .addComponent(HacerTransaccionCuentaOrigenLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HacerTransaccionCuentaDestinoInput, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HacerTransaccionCuentaOrigenInput, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HacerTransaccionTypeInput, 0, 485, Short.MAX_VALUE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(HacerTransaccionTitulo)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(255, 255, 255)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(HacerTransaccionTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HacerTransaccionTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HacerTransaccionTypeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HacerTransaccionCuentaOrigenInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HacerTransaccionCuentaOrigenLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HacerTransaccionCuentaDestinoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HacerTransaccionCuentaDestinoLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        PanelOpciones.addTab("Make Transaction", jPanel3);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("List Users");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Age", "Number of Accounts"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(88, 88, 88))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelOpciones.addTab("List Users", jPanel4);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("List Accounts");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "User ID", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jButton5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(90, 90, 90))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelOpciones.addTab("List Accounts", jPanel5);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("List Transactions");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type", "Source Account ID", "Destination Account ID", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable3);

        jButton6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(89, 89, 89))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelOpciones.addTab("List Transactions", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelOpciones)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistroUsuarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroUsuarioBotonActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(RegistroUsuarioIdInput.getText());
            String firstname = RegistroUsuarioFirstnameInput.getText();
            String lastname = RegistroUsuarioLastnameInput.getText();
            int age = Integer.parseInt(RegistroUsuarioAgeInput.getText());
            
            this.users.add(new User(id, firstname, lastname, age));
            
            RegistroUsuarioIdInput.setText("");
            RegistroUsuarioFirstnameInput.setText("");
            RegistroUsuarioLastnameInput.setText("");
            RegistroUsuarioAgeInput.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegistroUsuarioBotonActionPerformed

    private void CrearCuentaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCuentaBotonActionPerformed
        // TODO add your handling code here:
        try {
            int userId = Integer.parseInt(CrearCuentaIdUsuarioInput.getText());
            double initialBalance = Double.parseDouble(CrearCuentaBalanceInicialInput.getText());
            
            User selectedUser = null;
            for (User user : this.users) {
                if (user.getId() == userId && selectedUser == null) {
                    selectedUser = user;
                }
            }
            
            if (selectedUser != null) {
                Random random = new Random();
                int first = random.nextInt(1000);
                int second = random.nextInt(1000000);
                int third = random.nextInt(100);
                
                String accountId = String.format("%03d", first) + "-" + String.format("%06d", second) + "-" + String.format("%02d", third);
                
                this.accounts.add(new Account(accountId, selectedUser, initialBalance));
                
                CrearCuentaIdUsuarioInput.setText("");
                CrearCuentaBalanceInicialInput.setText("");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CrearCuentaBotonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            String type = HacerTransaccionTypeInput.getItemAt(HacerTransaccionTypeInput.getSelectedIndex());
            switch (type) {
                case "Deposit": {
                    String destinationAccountId = HacerTransaccionCuentaDestinoInput.getText();
                    double amount = Double.parseDouble(jTextField9.getText());
                    
                    Account destinationAccount = null;
                    for (Account account : this.accounts) {
                        if (account.getId().equals(destinationAccountId)) {
                            destinationAccount = account;
                        }
                    }
                    if (destinationAccount != null) {
                        destinationAccount.deposit(amount);
                        
                        this.transactions.add(new Transaction(TransactionType.DEPOSIT, null, destinationAccount, amount));
                        
                        HacerTransaccionCuentaOrigenInput.setText("");
                        HacerTransaccionCuentaDestinoInput.setText("");
                        jTextField9.setText("");
                    }
                    break;
                }
                case "Withdraw": {
                    String sourceAccountId = HacerTransaccionCuentaOrigenInput.getText();
                    double amount = Double.parseDouble(jTextField9.getText());
                    
                    Account sourceAccount = null;
                    for (Account account : this.accounts) {
                        if (account.getId().equals(sourceAccountId)) {
                            sourceAccount = account;
                        }
                    }
                    if (sourceAccount != null && sourceAccount.withdraw(amount)) {
                        this.transactions.add(new Transaction(TransactionType.WITHDRAW, sourceAccount, null, amount));
                        
                        HacerTransaccionCuentaOrigenInput.setText("");
                        HacerTransaccionCuentaDestinoInput.setText("");
                        jTextField9.setText("");
                    }
                    break;
                }
                case "Transfer": {
                    String sourceAccountId = HacerTransaccionCuentaOrigenInput.getText();
                    String destinationAccountId = HacerTransaccionCuentaDestinoInput.getText();
                    double amount = Double.parseDouble(jTextField9.getText());
                    
                    Account sourceAccount = null;
                    Account destinationAccount = null;
                    for (Account account : this.accounts) {
                        if (account.getId().equals(sourceAccountId)) {
                            sourceAccount = account;
                        }
                    }
                    for (Account account : this.accounts) {
                        if (account.getId().equals(destinationAccountId)) {
                            destinationAccount = account;
                        }
                    }
                    if (sourceAccount != null && destinationAccount != null && sourceAccount.withdraw(amount)) {
                        destinationAccount.deposit(amount);
                        
                        this.transactions.add(new Transaction(TransactionType.TRANSFER, sourceAccount, destinationAccount, amount));
                        
                        HacerTransaccionCuentaOrigenInput.setText("");
                        HacerTransaccionCuentaDestinoInput.setText("");
                        jTextField9.setText("");
                    }
                    break;
                }
                default: {
                    HacerTransaccionCuentaOrigenInput.setText("");
                    HacerTransaccionCuentaDestinoInput.setText("");
                    jTextField9.setText("");
                    break;
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        this.users.sort((obj1, obj2) -> (obj1.getId() - obj2.getId()));
        
        for (User user : this.users) {
            model.addRow(new Object[]{user.getId(), user.getFirstname() + " " + user.getLastname(), user.getAge(), user.getNumAccounts()});
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        
        this.accounts.sort((obj1, obj2) -> (obj1.getId().compareTo(obj2.getId())));
        
        for (Account account : this.accounts) {
            model.addRow(new Object[]{account.getId(), account.getOwner().getId(), account.getBalance()});
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        
        ArrayList<Transaction> transactionsCopy = (ArrayList<Transaction>) this.transactions.clone();
        Collections.reverse(transactionsCopy);
        
        for (Transaction transaction : transactionsCopy) {
            model.addRow(new Object[]{transaction.getType().name(), (transaction.getSourceAccount() != null ? transaction.getSourceAccount().getId() : "None"), (transaction.getDestinationAccount()!= null ? transaction.getDestinationAccount().getId() : "None"), transaction.getAmount()});
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CrearCuenta;
    private javax.swing.JTextField CrearCuentaBalanceInicialInput;
    private javax.swing.JLabel CrearCuentaBalanceInicialLabel;
    private javax.swing.JButton CrearCuentaBoton;
    private javax.swing.JTextField CrearCuentaIdUsuarioInput;
    private javax.swing.JLabel CrearCuentaIdUsuarioLabel;
    private javax.swing.JLabel CrearCuentaTituloLabel;
    private javax.swing.JTextField HacerTransaccionCuentaDestinoInput;
    private javax.swing.JLabel HacerTransaccionCuentaDestinoLabel;
    private javax.swing.JTextField HacerTransaccionCuentaOrigenInput;
    private javax.swing.JLabel HacerTransaccionCuentaOrigenLabel;
    private javax.swing.JLabel HacerTransaccionTitulo;
    private javax.swing.JComboBox<String> HacerTransaccionTypeInput;
    private javax.swing.JLabel HacerTransaccionTypeLabel;
    private javax.swing.JTabbedPane PanelOpciones;
    private javax.swing.JPanel RegistroUsuario;
    private javax.swing.JTextField RegistroUsuarioAgeInput;
    private javax.swing.JLabel RegistroUsuarioAgeLabel;
    private javax.swing.JButton RegistroUsuarioBoton;
    private javax.swing.JTextField RegistroUsuarioFirstnameInput;
    private javax.swing.JLabel RegistroUsuarioFirstnameLabel;
    private javax.swing.JTextField RegistroUsuarioIdInput;
    private javax.swing.JLabel RegistroUsuarioIdLabel;
    private javax.swing.JTextField RegistroUsuarioLastnameInput;
    private javax.swing.JLabel RegistroUsuarioLastnameLabel;
    private javax.swing.JLabel RegistroUsuarioTituloLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
